### ISSUE TITLE
Node package v3.1.0 isn't published to the public npm registry

### ISSUE THREAD

**Issue by nicexe** [OpenZeppelin/openzeppelin-contracts-upgradeable#100]
The latest available version is 3.0.0

**Comment by abcoathup** [comment]
Hi @nicexe,

OpenZeppelin Contracts Ethereum Package 3.0.0 is currently the latest version.

See the plan for improving the release cadence of the upgrade safe fork: https://forum.openzeppelin.com/t/the-future-of-contracts-ethereum-package/3642

**Comment by frangio** [comment]
For various reasons we've skipped 3.1.0 and published 3.2.0 directly. Hope this works for you. Let me know otherwise.
