### ISSUE TITLE
Solidity 0.7.4 support

### ISSUE THREAD

**Issue by ebulku** [OpenZeppelin/openzeppelin-contracts-upgradeable#103]
**📝 Details**
Is there any solidity 0.7 support?

**Comment by frangio** [comment]
Publishing 0.7 support is not an immediate priority for us but we're gathering requests to understand how much interest there is in it. Will keep yours in mind!

**Comment by frangio** [comment]
@ebulku Solidity 0.7 support has been released in version `3.2.0-solc-0.7`. Install with:

```
npm install @openzeppelin/contracts-upgradeable@solc-0.7
```
