### ISSUE TITLE
Applying renamings to documentation comments

### ISSUE THREAD

**Issue by Skyge** [OpenZeppelin/openzeppelin-contracts-upgradeable#104]
Glad to see have a new release version, and I am trying to use the latest version right now, but I am confused about this comments: [To use this library you can add a `using SafeERC20 for IERC20;` statement to your contract,](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC20/SafeERC20Upgradeable.sol#L15)
Should it be `using SafeERC20Upgradeable for IERC20Upgradeable;`

**Comment by frangio** [comment]
Hi @Skyge. Yes, indeed. While the code is converted automatically, the documentation comments are kept the same. It would be difficult for us to do that automatically, but we may be able to work something out for the [docs site](https://docs.openzeppelin.com).

**Comment by frangio** [comment]
As explained in [Using with Upgrades](https://docs.openzeppelin.com/contracts/3.x/upgradeable#usage):

>The package replicates the structure of the main OpenZeppelin Contracts package, but every file and contract has the suffix `Upgradeable`.

**Comment by stefek99** [comment]
Thank you very much for renaming the package!

- `OpenZeppelin/openzeppelin-contracts`
- `OpenZeppelin/openzeppelin-contracts-upgradeable` - logical, upgradeable

"ethereum package" was totally unintuitive

`import "@openzeppelin/contracts-ethereum-package/contracts/presets/ERC20PresetMinterPauser.sol";`

**Comment by frangio** [comment]
Closing in favor of #105.
