### ISSUE TITLE
TransferFrom don't check the sender, with function internal _msg.sender() like doit tranfer!!!

### ISSUE THREAD

**Issue by alfredolopez80** [OpenZeppelin/openzeppelin-contracts-upgradeable#107]
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/c0b9fd6e81c00000dc0749aa116a7735f0d35fe3/contracts/token/ERC20/ERC20Upgradeable.sol#L159

If you verify the flow of the TransferFrom function, you can verify how _transfer is called and not transfer, the sender is not validated at any time with the _msg.sender () function, which in theory allows transferring from another address and make the transfer if said address is allowed to do so, a situation that should not arise!
I may be overlooking something but it caught my attention by following the flow that this verification was not done, which in the transfer function it is done!

**Comment by frangio** [comment]
Hi @alfredolopez80, thanks for your question. This is hard to see but if `msg.sender` doesn't have allowance the function will revert when we attempt to subtract the transferred amount from the current allowance in the following line.

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/c0b9fd6e81c00000dc0749aa116a7735f0d35fe3/contracts/token/ERC20/ERC20Upgradeable.sol#L160
