### ISSUE TITLE
Using IERC721EnumerableUpgradeable

### ISSUE THREAD

**Issue by Kampe** [OpenZeppelin/openzeppelin-contracts-upgradeable#108]
Hello!

Been browsing around, and noticed there's no documentation on using IERC721EnumerableUpgradeable, and it doesn't seem to work as the ERC721Upgradeable does.

Specifically, how does one initialize it properly?

I've tried:

```
  function initialize() initializer public {
    __IERC721Enumberable_init("test", "TEST");
  }
```
But this doesn't seem to be the answer.

Any assistance in the right direction would be appreciated.

**Comment by frangio** [comment]
Hi @Kampe, the contract you asked about is an interface (as hinted by the `I` prefix), so there is no way to initialize it.

If you want an enumerable ERC721 contract, you should use the `ERC721Upgradeable` contract. And your initializer will look something like:

```solidity
  function initialize() initializer public {
    __ERC721_init("test", "TEST");
  }
```

**Comment by Kampe** [comment]
Right, but how does one create an enumerated upgradable erc721 contract?  The interface is here..

**Comment by frangio** [comment]
Sorry I may not have been clear before. Our `ERC721` contract (including `ERC721Upgradeable`) is enumerable by default.

As you can see in the code it implements the `IERC721EnumerableUpgradeable` interface:

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/c4edd76504b3ad95d11bbef8d558c171d6492922/contracts/token/ERC721/ERC721Upgradeable.sol#L22

**Comment by Kampe** [comment]
Aha, that makes sense :)

Thanks for clarifying!
