### ISSUE TITLE
Wrong content on release v3.4.0-solc-0.7

### ISSUE THREAD

**Issue by leckylao** [OpenZeppelin/openzeppelin-contracts-upgradeable#113]
**💻 Environment**

Now I am using `3.4.1-solc-0.7-2` with Hardhat. 

**📝 Details**

I was trying to upgrade the library with solc 0.7 support and `v3.4.0-solc-0.7` is the latest solc 0.7 version, but the npm install from npmjs.com content is wrong as it's using ERC20 instead of ERC20Upgradable and my compile failed. Then I realised there's `3.4.1-solc-0.7-2` on npmjs.com but not on GitHub release. Now I am using the 0.7-2 version and has no problem. 

Therefore I suggest adding the `3.4.1-solc-0.7-2` tag on Github and ask people to use `3.4.1-solc-0.7-2` instead of `3.4.0-solc-0.7`

**🔢 Code to reproduce bug**

```
npm install @openzeppelin/contracts-upgradeable@3.4.0-solc-0.7
```

**Comment by Amxx** [comment]
Hello @leckylao, and thank you for raising that issue.

We did encounter an issue when publishing `3.4.1-solc-0.7` on npm, which required us to have this `-2` fix. We are aware that this might cause issues, like the one you have been facing, and we are sorry for that.

We will take measures shortly to improve the situation.

**Comment by frangio** [comment]
npm doesn't allow unpublishing this version, but I've placed a deprecation noticed.
