### ISSUE TITLE
parameter name is unused

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-contracts-upgradeable#116]
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/c00ef11f5a926b579f5466132d238762af41dd23/contracts/token/ERC20/extensions/draft-ERC20PermitUpgradeable.sol#L38

&& 

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/c00ef11f5a926b579f5466132d238762af41dd23/contracts/token/ERC20/extensions/draft-ERC20PermitUpgradeable.sol#L41

Is it there for a reason?

**Comment by frangio** [comment]
See https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/issues/89#issuecomment-674236180
