### ISSUE TITLE
Please release v4.3.0 as a github release

### ISSUE THREAD

**Issue by PatrickAlphaC** [OpenZeppelin/openzeppelin-contracts-upgradeable#120]
It looks like we have 4.3.0 of the npm package, but not the github release.

The python smart contract development framework [brownie](https://github.com/eth-brownie/brownie) relies on github releases instead of npm, and right now the latest github release is v4.2.0.

Could we please sync them to both be 4.3.0? I am looking to create some content on your governance contracts.

Thank you!

Perhaps this is a good time to suggest having the npm release process be a github action after you publish a release in github? It would automate the two of these tasks so they will always be in sync.

**Comment by Amxx** [comment]
Hello @PatrickAlphaC 

Is [that release](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v4.3.0) not visible/working for you?

Thanks for the suggestion of having the release automated through github. I'm not 100% sure how we would handle the pre-release process, but we will definitely consider that.

**Comment by frangio** [comment]
I think @PatrickAlphaC was referring to this Upgradeable repo. 4.3 was missing, I've just added it.

**Comment by PatrickAlphaC** [comment]
Exactly, thank you @frangio !
