### ISSUE TITLE
Writting tests for ERC20 Upgradeable contract

### ISSUE THREAD

**Issue by bloomverga** [OpenZeppelin/openzeppelin-contracts-upgradeable#128]
**🧐 Motivation**

Test written for ERC20 are for the classical (non-upgradeable) ERC20 contract. See [ERC20.test.js](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/test/token/ERC20/ERC20.test.js)

An update is needed for the written tests in other to make them compatible with Upgradeable contracts.

**📝 Details**

Here the non-upgradeable mock contracts are used instead of the upgradeable ones.
```
const ERC20Mock = artifacts.require('ERC20Mock');
const ERC20DecimalsMock = artifacts.require('ERC20DecimalsMock');
```

Contract is instantiated via a constructor instead of using a deployProxy method.
```
  beforeEach(async function () {
    this.token = await ERC20Mock.new(name, symbol, initialHolder, initialSupply);
  });
}
```

**Comment by frangio** [comment]
All of the tests in this repository work in this way. We're testing the logic of the contract itself, not through a proxy, and we consider that sufficient for the purposes of this test suite.
