### ISSUE TITLE
Missing StrStringsUpgradeableString is causing tests to fail

### ISSUE THREAD

**Issue by j-mmyx** [OpenZeppelin/openzeppelin-contracts-upgradeable#130]
**📝 Details**

The CI tests for this repo are failing because there is an undeclared identifier in [ECDSAUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/cryptography/ECDSAUpgradeable.sol#L219). On line 219, `StrStringsUpgradeableString` does not resolve to anything. Instead, it should use `StringsUpgradeable.toString()`

**🔢 Code to reproduce bug**

See the CI logs: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/runs/4027734122?check_suite_focus=true

**Comment by frangio** [comment]
Resolved by https://github.com/OpenZeppelin/openzeppelin-transpiler/commit/b3c645661038bdbe81cda258f73cfd6722b224b5.
