### ISSUE TITLE
Use `extcodehash` instead of `extcodesize`

### ISSUE THREAD

**Issue by abhi3700** [OpenZeppelin/openzeppelin-contracts-upgradeable#135]
**🧐 Motivation**
This is for saving gas by 300 unit.

**📝 Details**
The `extcodesize` uses 300 gas more than `extcodehash` to determine whether or not an address is a contract. Hence, this is pertaining to that.

This [line-27](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/AddressUpgradeable.sol#L27) refers to the `isContract` function in `AddressUpgradeable.sol` file. This function is supposed to modified to this:
```
function isContract(address account) public view returns (bool) {
    bytes32 hash;
    assembly {
        hash := extcodehash(account)
    }
    return (hash != 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470);
}
```

**Comment by Amxx** [comment]
Hello @abhi3700 

I think this is a really interesting proposal. It should however be done on the [@openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) repository. Can you please open an issue there?

**Comment by frangio** [comment]
See https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1802#issuecomment-657668876. We used `extcodehash` in the past but went back to `extcodesize` as it was shown to be more efficient. If this is no longer the case please open another issue.
