### ISSUE TITLE
 High Impact Slither static analysis issue for OwnableUpgradeable contract

### ISSUE THREAD

**Issue by sudeepb02** [OpenZeppelin/openzeppelin-contracts-upgradeable#136]
The static analysis tool Slither is displaying a high impact issue for variable shadowing in it's code analysis. The finding is in the `openzeppelin-contracts-upgradeable` package itself. More details for the issue below:

**Contract Name:** `OwnableUpgradeable.sol`
**Package version:** `"@openzeppelin/contracts-upgradeable": "^4.3.3"`

Detailed message:
```
⸻⸻ Detailed Result Output ⸻⸻

Type: State variables shadowing (shadowing-state)

Impact: High

Confidence: High

Finding:

❌ OwnableUpgradeable.__gap (@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol:74) shadows:

• ContextUpgradeable.__gap (@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol#31)

Recommendation: Remove the state variable shadowing.

Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#state-variable-shadowing

⸻⸻⸻⸻⸻⸻⸻⸻
```

## Steps to reproduce
- Create a new Hardhat sample project
- Install `@openzeppelin/contracts-upgradeable` package and import `OwnableUpgradeable.sol`
- Inherit `OwnableUpgradeable` for the Greeter sample contract
- Run Slither static analysis test

As it is a high impact issue and deals with the `_gap` variable, could it result in data corruption for other state variables during upgrades?

**Comment by Amxx** [comment]
_gap variables are not used anywhere (not written to or read from). If we could have storage slots reserved with no name we would ... but we have to give them a name.

Shadowing of the _gap variables is NOT an issue.

**Comment by sudeepb02** [comment]
Correct me if I'm wrong, isn't the `_gap` variable used to determine the available free space(reserved space) for storing state variables that might be added in the future during upgrades? And if that is the case, what happens if during upgrade the contract overwrites an existing state variable because of inconsistent value of the `_gap` variable? A detailed explanation or a link to one would definitely help me understand this issue. Thanks

**Comment by Amxx** [comment]
The is what the [upgrades plugin](https://docs.openzeppelin.com/upgrades-plugins/1.x/) checks, and that is why we insist people use it when they can.

When you deploy a proxy (with the plugin), a snapshot of the storage layout is taken, which is then used, during a subsequent upgrade, to check that the new storage is compatible with the old one.

**Comment by frangio** [comment]
Thanks for the issue.

An explanation of the gap storage variable is found [here](https://docs.openzeppelin.com/contracts/4.x/upgradeable#storage_gaps).

Technically there is no variable shadowing here because the variables are private, so the Slither issue is misleading. In any case, the variables are not used in the Solidity code so I would not consider the shadowing would an issue.

**Comment by sudeepb02** [comment]
@Amxx @frangio Thanks for the explanation and the links, really helps understand the issue.
