### ISSUE TITLE
Slither Static Analysis: Reentrancy in ERC1967UpgradeUpgradeable._upgradeToAndCallSecure(address,bytes,bool)

### ISSUE THREAD

**Issue by iam-dev** [OpenZeppelin/openzeppelin-contracts-upgradeable#137]
Using Slither static analysis

**💻 Environment**
 "@openzeppelin/contracts-upgradeable": "^4.4.1",
Node version: v16.13.1
yarn run v1.22.17
$ slither . --detect reentrancy-eth,reentrancy-no-eth,reentrancy-benign,reentrancy-events,reentrancy-unlimited-gas
'npx hardhat compile --force' running
hardhat solidity version 0.8.8

Compilation finished successfully

 "@openzeppelin/contracts-upgradeable": "^4.4.1",
hardhat solidity version 0.8.8 
**📝 Details**
Reentrancy in ERC1967UpgradeUpgradeable._upgradeToAndCallSecure(address,bytes,bool) (node_modules/@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol#87-115):
	External calls:
	- _functionDelegateCall(newImplementation,data) (node_modules/@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol#97)
		- (success,returndata) = target.delegatecall(data) (node_modules/@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol#212)
	- _functionDelegateCall(newImplementation,abi.encodeWithSignature(upgradeTo(address),oldImplementation)) (node_modules/@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol#105-108)
		- (success,returndata) = target.delegatecall(data) (node_modules/@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol#212)
	Event emitted after the call(s):
	- Upgraded(newImplementation) (node_modules/@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol#63)
		- _upgradeTo(newImplementation) (node_modules/@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol#113)
		

**🔢 Code to reproduce bug**
- yarn
- yarn compile
- pip3 install slither-analyzer
-  yarn slither (slither . --detect reentrancy-eth,reentrancy-no-eth,reentrancy-benign,reentrancy-events,reentrancy-unlimited-gas)

**Comment by frangio** [comment]
This is probably in the category `reentrancy-benign`, as the name says it's not cause for concern.
