### ISSUE TITLE
ERC1967UpgradeUpgradeable uses pragma solidity ^0.8.2;

### ISSUE THREAD

**Issue by sdelvalle57** [OpenZeppelin/openzeppelin-contracts-upgradeable#138]
ERC1967UpgradeUpgradeable is using pragma 0.8.2 while all the others use 0.8.0

**💻 Environment**

Using truffle this leads to a solc issue

**📝 Details**

![image](https://user-images.githubusercontent.com/12821552/148583379-00f1dcb3-48a9-41b3-bba8-d1d54926b244.png)

**🔢 Code to reproduce bug**
Using truffle compile

**Comment by Amxx** [comment]
Some contracts need features that were introduced after 0.8.0. In this particular case, it has to do with the custom NatSpec, that the upgrades plugins relies on, and that the compiler didn't recognize until 0.8.2. Other contracts in our codebase will require 0.8.4

If you need to use this file, you should update your compiler to 0.8.2 or above. Also, it is in general good practice to use a more recent version of the compiler.
