### ISSUE TITLE
ERC20Votes should initialize inheritance

### ISSUE THREAD

**Issue by chichke** [OpenZeppelin/openzeppelin-contracts-upgradeable#141]
### Current state 

```solidity
function __ERC20Votes_init_unchained() internal onlyInitializing {}
```

### What we could do 

```solidity
    function __ERC20Votes_init(string memory name_, string memory symbol_) internal onlyInitializing {
        __ERC20Permit_init(name_);
        __ERC20_init(name_, symbol_);
    }

  function __ERC20Votes_init_unchained(string memory name_, string memory symbol_) internal onlyInitializing {

    }
```

It would simplify our initialize function
Have a great day OZ team

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC20/extensions/ERC20VotesUpgradeable.sol

**Comment by Amxx** [comment]
Hello @chichke 

The contracts present in the repo are directly transpiled for from `@openzeppelin/contracts` repo/package. The initializers in the upgradeable contracts are a simple translation of the constructors in the "vanilla" contract.

For ERC20VotesUpgradeable, the current interface is the result of [ERC20Votes](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Votes.sol) not calling its parent constructor. This is a rule we have in all token extensions to avoid possible constructor conflicts.

If you are having difficulty writing a upgradeable ERC20 contract with the necessary extensions, please try out the [contract Wizard](https://wizard.openzeppelin.com/).

**Comment by chichke** [comment]
Thanks for the answer @Amxx, I think the contract wizard is good but you can avoid these overrides by inheriting from ERC20Votes only, since it is inherited itself from ERC20Permit, which is inherited from ERC20
```solidity
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/draft-ERC20Permit.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol";

contract MyToken is ERC20, ERC20Permit, ERC20Votes
```

**Comment by frangio** [comment]
@chichke Thanks for the suggestion. The change that you propose is incompatible with the way that these contracts are defined in OpenZeppelin Contracts upstream. We recently added `ERC20Votes_init` which was missing, but you still need to invoke `ERC20Permit_init` and pass those parameters.
