### ISSUE TITLE
DocstringParsingError: Documentation tag @notice

### ISSUE THREAD

**Issue by wiasliaw** [OpenZeppelin/openzeppelin-contracts-upgradeable#146]
**🔢 Code to reproduce bug**

Compiling contract cause error of `DocstringParsingError`.  There should be a `@dev` for private in the begin.

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/5660d65e282a1b9c7379ba74461fa89c182e3fff/contracts/utils/ContextUpgradeable.sol?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L31-L36

![image](https://user-images.githubusercontent.com/37038019/153355834-fda6d1db-1f8e-444b-ac8a-e752efb2991c.png)

**Comment by ada173** [comment]
I am having this error as well with compiler version `0.8.2`
![image](https://user-images.githubusercontent.com/94717259/153504469-f2b096ae-63fe-4c19-a709-d2d5132392fc.png)

**Comment by wiasliaw** [comment]
@ada173 Use the newer version of compiler. `0.8.0`, `0.8.1`, `0.8.2` and `0.8.3` will cause that error for private state variables and there are some breaking change in `utils/Address.sol`.

@frangio I think it is easy to fix by specifying a tag `@dev`.

**Comment by frangio** [comment]
Fixed in 4.5.1 added `@dev`.
