### ISSUE TITLE
ERC2771ContextUpgradeable doesn't follow Upgradeable Pattern

### ISSUE THREAD

**Issue by tpae** [OpenZeppelin/openzeppelin-contracts-upgradeable#147]
I've upgraded my contracts to the latest `4.5` and noticed that I can no longer call `__ERC2771Context_init_unchained(trustedForwarder)` due to the immutable `_trustedForwarder` variable. This breaks the upgradeability pattern and there should be a way to work around this.

**💻 Environment**

`@openzeppelin/contracts-upgradeable@4.5.0`

**🔢 Code to reproduce bug**

Missing `__ERC2771Context_init_unchained` from the codebase. See https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/commit/842bef827058dc37b81bc0c96956bb381b6cf789

**Comment by tpae** [comment]
Related to: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2917

**Comment by Amxx** [comment]
Hello @tpae 

It was decided to use an immutable variable here because we thought the gas savings would be significant enough, and we did not imagine that multiple proxies using the same underlying implementation would want to use different trusted forwarders.

Are you using `ERC2771Context` with multiple forwarders? If so, my solution would be to build your own `ERC2771ContextFromStorage` module, that uses non-immutable variables, and includes an initializer.

Maybe we should provide both versions in the future @frangio

**Comment by tpae** [comment]
Hello @Amxx, thank you for your reply and suggestions. I'm not using multiple forwarders; I have a factory that instantiates minimal proxies with implementations that extends `ERC2771Context`.

My understanding is that when we instantiate a minimal proxy, it does not call the constructor which is required to set the initial values of the trusted forwarder. By defining the variable as immutable, does that mean our implementation contract will need to be deployed with a trusted forwarder address, and all of the instantiated proxies will use that same address?

I could build my own `ERC2771ContextFromStorage`, but I want to understand how to use `ERC2771ContextUpgradeable` in a way meant to be used.

**Comment by Amxx** [comment]
In that case you should use the new ERC2771ContextUpgradeable.

The good thing with immutable variables is that, once they are set at construction, minimal proxy that point to the implementation WILL not need to set these values in the constructor.

Here is an example
```
import "@openzeppelin/contracts/proxy/Clones.sol";

contract TestInstance {
    uint256 public immutable someValue;

    constructor(uint256 value) {
        someValue = value;
    }
}

contract TestFactory {
    address public immutable template = address(new TestInstance(17));

    function createClone() external returns (address) {
        address instance = Clones.clone(template);

//        require(TestInstance(instance).someValue() == 0, "this would fail");
        require(TestInstance(instance).someValue() == 17, "this will not fail");

        return instance;
    }
}
```

The bottom line is: when constructing the "template" for your proxy, use the constructor to set the immutable variable in the template. All the proxies will benefit from it, without requiring it to be set in the initializer.

This is cheaper to initialize AND cheaper to use.

**Comment by tpae** [comment]
Amazing! Thank you so much for your guidance!

**Comment by mvanmeerbeck** [comment]
Hello
My use case is a bit different. My erc20 will need to use metatx in the future but I don't have the trusted forwarder address yet so I cannot set it at deployment. How are we supposed to do in that case? Use the previous version?

**Comment by Amxx** [comment]
@mvanmeerbeck I would make your contract upgradeable, and add the trusted forwarder as part of a future upgrade.

**Comment by jtakalai** [comment]
If I use ERC2771ContextUpgradeable, do I need all of the following boilerplate code? Seems the contract won't compile without:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import "@openzeppelin/contracts-upgradeable/metatx/ERC2771ContextUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol";

contract MyContract is Initializable, ERC2771ContextUpgradeable, AccessControlUpgradeable {
    bytes32 public constant FORWARDER_ROLE = keccak256("FORWARDER_ROLE");
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() ERC2771ContextUpgradeable(address(0x0)) {}

    function initialize() public initializer {
        __AccessControl_init();
        _setupRole(ADMIN_ROLE, _msgSender());
        _setRoleAdmin(FORWARDER_ROLE, ADMIN_ROLE);
    }

    function isTrustedForwarder(address forwarder) public view override(ERC2771ContextUpgradeable) returns (bool) {
        return hasRole(FORWARDER_ROLE, forwarder);
    }

    function _msgSender() internal view virtual override(ContextUpgradeable, ERC2771ContextUpgradeable) returns (address sender) {
        return super._msgSender();
    }

    function _msgData() internal view virtual override(ContextUpgradeable, ERC2771ContextUpgradeable) returns (bytes calldata) {
        return super._msgData();
    }
}
```

notice especially `_msgData` and `_msgSender` which are only needed to disambiguate between ContextUpgradeable and ERC2771ContextUpgradeable. Am I doing something wrong here?

**Comment by bogdan** [comment]
It seems confusing that `ERC2771ForwarderUpgradeable` has `initialize` method unlike any other upgradable contract. Is there anything special about it too?

**Comment by frangio** [comment]
@bogdan All "standalone" contracts have initializers, there's a few more:

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/3d5fa5c24c411112bab47bec25cfa9ad0af0e6e8/scripts/upgradeable/transpile.sh#L41-L44

**Comment by julian-zamt-cf** [comment]
Hi, just to be cristal clear, when performing an upgrade of a contract that inherits from `ERC2771ContextUpgradeable`, the forwarder address should be set again?
i.e.:
Deployment:
```
await hre.upgrades.deployProxy(
      Implementation,
      [initializeParams],
      {
        initializer: 'initialize',
        kind: 'uups',
        constructorArgs: [trustedForwarderAddress],
      }
    );
```

And then during an upgrade
```
await hre.upgrades.upgradeProxy(
      proxyInstance,
      newImplementation,
      { kind: 'uups', constructorArgs: [trustedForwarderAddress] }
    );
```

Thanks for the clarification!

**Comment by frangio** [comment]
> when performing an upgrade of a contract that inherits from `ERC2771ContextUpgradeable`, the forwarder address should be set again?

Yes.
