### ISSUE TITLE
Contract interfaces are named "upgradable" even if not relevant

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/openzeppelin-contracts-upgradeable#149]
I believe the contract interface `IERC721Upgradeable` is identical to baseline `IERC721` in OpenZeppelin Contracts.

This file and contract interface could please be renamed to just `IERC721` to indicate that no new additional functionality is claimed over the baseline specification.

Likewise for other similar interfaces.

**Comment by frangio** [comment]
Duplicate of https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/issues/133.

This is a breaking change that we're likely implementing in the next major release.

**Comment by fulldecent** [comment]
Sorry for the dupe, nice thank you.
