### ISSUE TITLE
Commit 2924ea3 possibly broke ERC2771ContextUpgradeable.sol

### ISSUE THREAD

**Issue by MBRGA** [OpenZeppelin/openzeppelin-contracts-upgradeable#154]
ERC2771ContextUpgradeable.sol doesn't currently seem to be using the Initializable pattern. It seems that commit 2924ea3 deleted the ` __ERC2771Context_init` function (leaving the code in a broken state) and the following commit added a constructor instead of an initializer.

**💻 Environment**

@openzeppelin/contracts-upgradeable 4.5.2, solidity 0.8.12

**📝 Details**

I am trying to use the ERC2771Context in an upgradeable contract (technically I'm trying to work out how to get openGSN working with my code without making everything inherit from BaseRelayRecipient).

It doesn't seem to be possible to use the Upgradeable version of ERC2771Context properly at this point. This might be due to _trustedForwarder switching to immutable variable in the original ERC2771Context, so that it could no longer be assigned-to in the init function.

**Comment by Amxx** [comment]
Hello @MBRGA 

This concern was already discussed in #147.

**Comment by MBRGA** [comment]
Thank you, and sorry I missed that. It does seem like there needs to be some documentation on this - everything I've read seems to say Upgradeable contracts should never use a constructor.

**Comment by MBRGA** [comment]
Actually @Amxx, I'm still a bit confused. How would you handle this if you have need to set both mutable and immutable variables at construction/initialisation? In particular looking at a derived contract. Or maybe what I'm doing makes no sense in the first place.

In my case the contracts are long-lived and will be initialized very infrequently, so I suppose gas costs associated with initialization are minimal.

**Comment by Amxx** [comment]
The gas cost issue is not about the initialization that write the variable (only done once per instance) ... its the "reading" from storage.

I would expect almost all function to do `_msgSender()` at some point, and that will cost 2100 gas just to get the address of the forwarder ... unless this is immutable storage.

There are many examples of contract that use both immutable storage for things like forwarder (hardcoded for all instances) AND an initializer for the other variable that change between instances. [This](https://github.com/p00ls/contracts/blob/master/contracts/tokens/P00lsTokenCreator.sol) is an example of such contract (note that there is both a constructor AND an initializer)

**Comment by MBRGA** [comment]
@Amxx  Getting back to this late, but how do you handle deployment when there is both a constructor and an initializer? Looking at your code for P00lsTokenCreator I'm struggling to understand when the initializer is called. In particular, the documentation for deploying upgradeable contracts implies that the arguments to deployProxy go to the initializer, but in your example it appears to be the registry argument for the constructor?

**Comment by Amxx** [comment]
- The constructor is called when the implementation contract is deployed
- The initializer is called through the proxy (during proxy deployment)

```
upgrade.deployProxy(contract, <initializerArgument>, { constructorArgs : [ <constructorArguments> ] });
```

**Comment by MBRGA** [comment]
Thanks @Amxx, really appreciate it.
