### ISSUE TITLE
ERC2771ContextUpgradeable.sol to using init 

### ISSUE THREAD

**Issue by KfishNFT** [OpenZeppelin/openzeppelin-contracts-upgradeable#156]
**🧐 Motivation**
I read about this being changed to use an immutable trusted forwarder; however, an alternative is still not available. Could this possibly be an alternative to building our own?

**📝 Details**
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/pull/155

**Comment by Amxx** [comment]
See answer in PR
