### ISSUE TITLE
Compiler error: Documentation tag @custom:oz-upgrades-unsafe-allow not valid for contracts.

### ISSUE THREAD

**Issue by seanamani** [OpenZeppelin/openzeppelin-contracts-upgradeable#157]
**💻 Environment**
Use solc Version: 0.8.0+commit.c7dfd78e.

**📝 Details**
Compiler error: When compiling https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol#L50

error: Documentation tag @custom:oz-upgrades-unsafe-allow not valid for contracts.

**🔢 Code to reproduce bug**

1. Clone Repo
2. Flatten this file https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol to pull all the other dependencies.
3. Compile the contracts using solc 0.8.0 
4. you get the error 
       error: Documentation tag @custom:oz-upgrades-unsafe-allow not valid for contracts.

**Comment by frangio** [comment]
Thanks @seanamani. The minimum required Solidity version for this file is now 0.8.2. We forgot to bump the pragma.
