### ISSUE TITLE
Clearly explain differences with openzeppelin-solidity

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts-upgradeable#16]
It's not clear to users why this package exists, why they have to use it, if they have to install it side-by-side with OpenZeppelin, etc.

We should improve the README first and foremost, and also check if the ZeppelinOS docs make all of this clear enough.

Additionally we should explain to people how they are expected to reuse the OpenZeppelin contracts that are on-chain within their custom systems.

**Comment by nfurfaro** [comment]
I think this issue needs attention, as I'm currently having difficulty navigating through some of these decisions!

**Comment by nventuro** [comment]
I believe the ZeppelinOS team is in the processes of producing some docs which should help in this regard (cc @spalladino).

@nfurfaro, could you expand a bit on which areas you find confusing? Thanks!

**Comment by nfurfaro** [comment]
@nventuro Sure, I'll write up a quick summary now.

**Comment by nfurfaro** [comment]
Seeking Clarification:

### Questions
- Must I use `openzepplen-eth` if trying to use `zOS`?
- If I need to make use of a contract other than the 6 currently deployed for `openzepplen-eth`, do I then use `openzepplen-solidity` as well? ie: It doesn't appear as though `Ownable.sol` is available on-chain, at least from the docs here: https://docs.zeppelinos.org/docs/stdlib.html
- In the docs under ["Testing Upgradeable Projects"](https://docs.zeppelinos.org/docs/testing.html), I see that `zos` provides a `TestHelper()` function. The example demonstrates creating a proxy with 
`const proxy = await this.project.createProxy(Sample);`, but it's not clear whether this is a "normal" proxy or an `AdminUpgradeabilityProxy`. Our tests currently use `this.proxy = await AdminUpgradeabilityProxy.new(implV1.address, initV1Call, { from: proxyAdmin })`. 

### Context
- The project I'm working on was started using truffle, and has `"openzeppelin-solidity": "^1.12.0"` as a dependency.
- We've recently started using the zOS cli to deploy and manage upgradeability. (We're currently using a global installation of `zos`).
- `"zos-lib": "^2.0.1"` is now a dependency as well, as it's needed for our testing.
### Project Architecture
At a high level, our project uses a "contract-factory" pattern, where a smart contract `Unlock.sol` can be called to deploy new `Lock.sol` contracts. We're using zOS (via the cli) to make `Unlock.sol` upgradeable. `Lock.sol` is *not* upgradeable. As far as zos or openzepplin-related imports in `Unlock.sol`, we currently import: 
- "openzeppelin-solidity/contracts/ownership/Ownable.sol";
- "zos-lib/contracts/Initializable.sol"; 

### Testing
Here is a snippet from one of our tests, `UnlockProxy.js` where I'm currently have trouble (I'm not the original author of this test). This was working fine, until a recent attempt to upgrade to `"openzeppelin-solidity": "^2.0.0"`. It seems that there have been some changes in the visibility of the `address _owner` and how it needs to be set. 

```
const zos = require('zos-lib')
const Unlock = artifacts.require('Unlock')
const UnlockTestV2 = artifacts.require('UnlockTestV2')
const UnlockTestV3 = artifacts.require('UnlockTestV3')
const AdminUpgradeabilityProxy = zos.Contracts.getFromNodeModules('zos-lib', 'AdminUpgradeabilityProxy')
const shared = require('./behaviors/shared')
const Units = require('ethereumjs-units')

contract('Unlock', function (accounts) {
  const proxyOwner = accounts[1]
  const unlockOwner = accounts[2]

  describe('Proxy Unlock contract', function () {
    beforeEach(async function () {
      const implV1 = await Unlock.new()
      const initV1Call = zos.encodeCall('initialize', ['address'], [unlockOwner])
      this.proxy = await AdminUpgradeabilityProxy.new(implV1.address, initV1Call, { from: proxyOwner })
      this.unlock = await Unlock.at(this.proxy.address)
    })

```
### Summary
While I have listed a few questions above, the biggest problem right now seems to be related to ownership details and proxy creation. It should be noted that the snippet above is not causing problems when using `"openzeppelin-solidity": "^1.12.0"`, but fails when trying to upgrade to `"openzeppelin-solidity": "^2.0.0"`. To be clear, this upgrade of oz-solidity necesitated changes in many places in the project, but I've not been able to solve this one. An incomplete understanding of the relationship between zOS, oz-solidity & oz-eth is compounding the difficulty of solving the problem.

Please feel free to ask for detail. clarification if it would be helpful. The project repo can be found here if needed:
https://github.com/unlock-protocol/unlock/tree/master/smart-contracts

**Comment by spalladino** [comment]
@nfurfaro this is awesome, thanks so much for the detailed feedback! We'll be tackling this the upcoming week, and get back to you for more input :-)

**Comment by nfurfaro** [comment]
No problem. Thanks for building an awesome project!
Update: In the snippet above I was not able to get it working, so I removed `AdminUpgradeabilityProxy.new` completely. The updated version works and looks like this:
```
const Unlock = artifacts.require('Unlock')
const UnlockTestV2 = artifacts.require('UnlockTestV2')
const UnlockTestV3 = artifacts.require('UnlockTestV3')
const Zos = require('zos')
const TestHelper = Zos.TestHelper
const shared = require('./behaviors/shared')
const Units = require('ethereumjs-units')

contract('Unlock', function (accounts) {
  const proxyAdmin = accounts[1]
  const unlockOwner = accounts[2]

  describe('Proxy Unlock contract', function () {
    beforeEach(async function () {
      this.project = await TestHelper({ from: proxyAdmin })
      this.proxy = await this.project.createProxy(Unlock, { initMethod: 'initialize', initArgs: [unlockOwner], initFrom: unlockOwner })
      this.unlock = await Unlock.at(this.proxy.address)
    })
```

Essentially, in the first version, when I tried to call `this.unlock.owner()` after everything was deployed, I kept getting `0x000000000000000000000` as a return value, seemingly no matter which address I used to deploy `Unlock`, or which address I used to call the `owner()` function.

**Comment by frangio** [comment]
Fixed with the guide now published at https://docs.openzeppelin.com/contracts/upgradeable.
