### ISSUE TITLE
interface IERC20Mintable and IERC20Burnable is needed

### ISSUE THREAD

**Issue by guotie** [OpenZeppelin/openzeppelin-contracts-upgradeable#169]
**🧐 Motivation**

I think interface IERC20Mintable and IERC20Burnable is needed.

**📝 Details**

for example, if I inherit the `ERC20PresetMinterPauserUpgradeable` as following:

```
contract MyToken is
    Initializable,
    UUPSUpgradeable,
    ERC20PresetMinterPauserUpgradeable,
    OwnableUpgradeable {
}
```

If I want call the `MyToken` method `mint`, then I need define an interface like this:
```
interface IMyToken {
    function mint(address to, uint256 amount) external;
}

contract MyToken is
    Initializable,
    UUPSUpgradeable,
    ERC20PresetMinterPauserUpgradeable,
    IMyToken,
    OwnableUpgradeable {
}
```

then, compile error:

```
Derived contract must override function "mint". Two or more base classes define function with same name and parameter types.

```

**Comment by guotie** [comment]
solidity version is ^0.8.0

**Comment by frangio** [comment]
> If I want call the `MyToken` method `mint`, then I need define an interface like this:

You don't need to define an interface. You can just use MyToken.

If you need further assistance post on the [OpenZeppelin Forum](https://forum.openzeppelin.com).
