### ISSUE TITLE
Constructor parameter included in upgradeable smart contract

### ISSUE THREAD

**Issue by eliashezron** [OpenZeppelin/openzeppelin-contracts-upgradeable#180]
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/a78956e979e126e942d8bdf8a6ed693f57c19c0e/contracts/metatx/ERC2771ContextUpgradeable.sol#L17

As a best practice, it is advisable not to include a constructor in upgradeable smart contracts due to the [constructor caveat](https://docs.openzeppelin.com/upgrades-plugins/1.x/proxies#the-constructor-caveat). 
However, this particular contract has a constructor included. Since the value, it modifies is immutable, you have to include it in the constructor.  Else the forwarder address should not be immutable.

what do you suggest would be a better way to write it without the need of having a constructor?

**Comment by Amxx** [comment]
See #181 (and #155)
