### ISSUE TITLE
gap ERC20WrapperUpgradeable is wrong.

### ISSUE THREAD

**Issue by novaknole** [OpenZeppelin/openzeppelin-contracts-upgradeable#188]
It's pretty easy what I have to report and you might be aware of already.

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/dd8ca8adc47624c5c5e2f4d412f5f421951dcc25/contracts/token/ERC20/extensions/ERC20WrapperUpgradeable.sol#L83

Here, gap should be 49.

**Comment by novaknole** [comment]
we're already using `4.8.1` version, so would appreciate if you could be careful with this.

**Comment by Amxx** [comment]
Hello @novaknole 

you can see in the comments that this contract specifically uses [a total size (storage + gap) of 51
](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/dd8ca8adc47624c5c5e2f4d412f5f421951dcc25/contracts/token/ERC20/extensions/ERC20WrapperUpgradeable.sol#L19)

This is to achieve compatibility with previous version that had a bug. This layout is going to be kept.
