### ISSUE TITLE
Missing function clock() and CLOCK_MODE() in GovernorVotesUpgradeable.sol

### ISSUE THREAD

**Issue by tbocek** [OpenZeppelin/openzeppelin-contracts-upgradeable#192]
I was looking into https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/extensions/GovernorVotes.sol, which has a clock function that one can overwrite. For upgradable GovernorVotes contracts, these clock methods are missing in https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/governance/extensions/GovernorVotesUpgradeable.sol

**💻 Environment**

any

**📝 Details**

Missing functions:

function clock() public view virtual override returns (uint48)
function CLOCK_MODE() public view virtual override returns (string memory)
in
GovernorVotesUpgradeable.sol

**🔢 Code to reproduce bug**

try to overwrite clock() with upgradeable contracts in GovernorVotesUpgradeable.sol. It works for non-upgradeable contracts not not for upgradeable contracts.

Error message:

```
TypeError: Function has override specified but does not override anything.
  --> contracts/ffs-vote.sol:44:42:
   |
44 |     function clock() public view virtual override returns (uint48) {
   |                                          ^^^^^^^^
```

**Comment by Amxx** [comment]
Hello @tbocek 

The upgradeable code in this repo is produced automatically by the transpiler. Unfortunatelly, some recent changes to the way unit tests are performed on the main (non upgradeable) repo have broken this transpilation process. This is commits to the main repo are not being reflected here.

We have been working on a new transpilation process, that is less maintenance heavy ... but this is still WIP. I'll see if we can fix it here.
