### ISSUE TITLE
Review constant state variables inlining

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts-upgradeable#20]
We currently have some constant state variables that are defined next to the declaration in the contracts, like:

```solidity
contract Foo {
  uint public constant x = 1234;
}
```

This works because the value is inlined into the bytecode and not written to storage. If it was written to storage it would be a problem because it would be written in the storage of the implementation whereas the proxy would try to read it from its own storage. Note that this kind of variable definition is an implicit part of the constructor.

We've experimentally verified that the compiler behaves in this way (i.e. inlining the value) with `string`, `uint`, and `bytes4` types which are those found in OpenZeppelin 2.0. However, we are opening this issue because it is not really a guarantee of the compiler that this will always remain so. In fact, it would be correct if the compiler decided to write to storage and read from it. So we have to keep this in mind and review it.

**Comment by nventuro** [comment]
I opened an issue upstream: https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1391. Maybe we could develop a Solium rule to disallow this @elopio? I think it's a good practice, regardless of `initializer` concerns.

**Comment by elopio** [comment]
I'm not sure it's a good practice. We would be replacing a constant variable with a variable that can change it's value but never really does.

**Comment by elopio** [comment]
For non-constant, yes, this seems like a good rule to add.
I imagine it would be something like:
non-constant state variables shouldn't have explicit initialization when declared.
and, all state variables should be initialized in the constructor.

**Comment by frangio** [comment]
Closing this issue as this behavior of constant state variables is [documented by Solidity](https://docs.soliditylang.org/en/latest/contracts.html#constant-and-immutable-state-variables) and highly unlikely to change. If it were to change, it would be in a breaking release and we would find out about it, while our current published contracts wouldn't compile under the new version due to the pragma we use.
