### ISSUE TITLE
Add migration methods for ERC20 & ERC721 from oz-zos 1.9

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-contracts-upgradeable#30]
Due to the [added gaps for future compatibility](https://github.com/OpenZeppelin/openzeppelin-zos/pull/29), the storage layout of all contracts has changed from version 1.x to 2.0. In particular, this affects ERC20 and ERC721, the two most widely used contracts.

We should add a migration method from the old version of these contracts to the new ones. This method should know the storage layout for both the old and the new implementations, and copy them as needed. It is possible that the migration requires more than a single tx, since several balances may need to be copied.

This method should not in the regular contracts, but added as separate ones, similar to the ERC20Migration.

**Comment by frangio** [comment]
I don't think migrating from a contract without gaps to a contract with gaps is really feasible. Given that no user has requested this I feel comfortable closing the issue.
