### ISSUE TITLE
Compile error on duplicated Ownable when importing contracts from -zos and -solidity repos

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-contracts-upgradeable#4]
Given that some contracts are not included in `openzeppelin-zos`, users need to import them from `openzeppelin-solidity`, such as `Destructible`. However, that poses a problem, as `Destructible` imports
`Ownable` from `-solidity`, which clashes with the implementation provided in `-zos`, and fails with a compile error. This may affect any other contract that also extends from contracts from both repos. 

```solidity
import "openzeppelin-zos/contracts/ownership/Ownable.sol";
import "openzeppelin-zos/contracts/lifecycle/Pausable.sol";
import "openzeppelin-solidity/contracts/lifecycle/Destructible.sol";
import "openzeppelin-solidity/contracts/math/SafeMath.sol";
import "zos-lib/contracts/migrations/Migratable.sol";

contract MyContract is Migratable, Ownable, Pausable, Destructible {
  // ...
}
```

Note that, in this case, using `-solidity`'s `Destructible` would be an error, since its owner cannot be initialized on proxy creation due to lack of an initializer; but we should plan for users attempting to mix contracts from both repos.

**Comment by nventuro** [comment]
`openzeppelin-zos` will now include every contract from upstream, so this shouldn't be an issue any more.

**Comment by frangio** [comment]
The new `@openzeppelin/contracts-upgradeable` package adds a suffix to all contracts so contracts like `Ownable` will not clash.
