### ISSUE TITLE
Verify logic contracts when deployed on networks

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts-upgradeable#66]
**🧐 Motivation**
When `StandaloneERC20`, `StandaloneERC721`, `TokenVesting`, `PaymentSplitter` are deployed to networks (Mainnet, Kovan, Ropsten, and Rinkeby) they would ideally be verified on Etherscan, as can't verify using the CLI, so have to manually verify.

e.g. `StandaloneERC20` logic contract: https://ropsten.etherscan.io/address/0xe491769618d3acfbbdc403841a66fc1023e711c6#code

**📝 Details**

Create a `StandaloneERC20` contract:
```
$ npx oz create
No contracts found to compile.
? Pick a contract to instantiate @openzeppelin/contracts-ethereum-package/StandaloneERC20
? Pick a network ropsten
✓ Linked dependency @openzeppelin/contracts-ethereum-package 2.2.3
All contracts are up to date
? Do you want to call a function on the instance after creating it? Yes
? Select which function * initialize(name: string, symbol: string, decimals: uint8, initialSupply: uint256, initialHolder: address, minters: address[], pausers: address[])
? name (string): My Token
? symbol (string): TKN
? decimals (uint8): 18
? initialSupply (uint256): 10000e18
? initialHolder (address): 0x13ebd3443fa5575F0Eb173e323D8419F7452CfB1
? minters (address[]): 0x13ebd3443fa5575F0Eb173e323D8419F7452CfB1
? pausers (address[]): 0x13ebd3443fa5575F0Eb173e323D8419F7452CfB1
✓ Setting everything up to create contract instances
✓ Instance created at 0x8b5Cc25340457339AFB0F3b739214cD27aBE13aD
0x8b5Cc25340457339AFB0F3b739214cD27aBE13aD
```

The logic contract can't be verified using the CLI.  Ideally it would be verified when the Ethereum Package logic contracts are deployed to the networks.

```
$ npx oz verify
? Pick a network ropsten
A contract alias must be specified
```
`ropsten.json`
```
  "proxies": {
    "@openzeppelin/contracts-ethereum-package/StandaloneERC20": [
      {
        "address": "0x8b5Cc25340457339AFB0F3b739214cD27aBE13aD",
        "version": "2.2.3",
        "implementation": "0xe491769618D3acFbBdC403841a66FC1023E711C6",
        "admin": "0x94E01684a8853bb6Fb7F3bc71D2e0a02729B2D5D",
        "kind": "Upgradeable"
      }
    ]
  }
```
`StandaloneERC20` logic contract: https://ropsten.etherscan.io/address/0xe491769618d3acfbbdc403841a66fc1023e711c6#code

**Comment by stxphxn** [comment]
Is there any information on how to manually verify a StandaloneERC20 contract until this is fixed?

**Comment by buildog** [comment]
@abcoathup i'm stuck with `A contract alias must be specified` error, how can I manually verify a `StandaloneERC20` ?

**Comment by abcoathup** [comment]
Hi @buildog,

Would you mind posting this question in the Community Forum with the details of when you get the error: https://forum.openzeppelin.com/  Thanks.  

I will try to put together some instructions on manually verifying. (cc @stxphxn )

**Comment by abcoathup** [comment]
I manually verified contracts in [2.2.3](https://www.npmjs.com/package/@openzeppelin/contracts-ethereum-package/v/2.2.3)

StandaloneERC20: https://etherscan.io/address/0xb7f08c44086baa3c8e74b68e2817b5ae633770bf#code
StandaloneERC721: https://etherscan.io/address/0x856d154656930060f9999848690D1c06c7C5eFD1#code
TokenVesting: https://etherscan.io/address/0x6498CB302b94AD841BfeCfB55F56781dCDDA4754#code
PaymentSplitter: https://etherscan.io/address/0xc6c65338632a6e84f7d67c94eac117571932e95c#code

StandaloneERC20 (already verified): https://ropsten.etherscan.io/address/0xe491769618d3acfbbdc403841a66fc1023e711c6#code
StandaloneERC721: https://ropsten.etherscan.io/address/0xE77B22d034cF85F2F851516D9BdC2fF2D76471D3#code
TokenVesting: https://ropsten.etherscan.io/address/0x87C4eE5Ce946291BCcF4ac3333f44CFfDE26f98a#code
PaymentSplitter: https://ropsten.etherscan.io/address/0x621DB5C5B8A6CFd829bDAe49D0a2c2e90797Fc38#code

StandaloneERC20: https://rinkeby.etherscan.io/address/0x73fa66eA7944a51453e78970dC84634D91e4848c#code
StandaloneERC721: https://rinkeby.etherscan.io/address/0x7fe0a0e67409503cf795d47e1db0c77a2220210b#code
TokenVesting: https://rinkeby.etherscan.io/address/0x1e06b993696bd78871406baae1c473da23830acc#code
PaymentSplitter: https://rinkeby.etherscan.io/address/0xc0b7305Ce44b261332E548CC9E7FD3CAFb798426#code

StandaloneERC20: https://kovan.etherscan.io/address/0xaabc7f35af87b61148cd4047828cc7fc0707d771#code
StandaloneERC721: https://kovan.etherscan.io/address/0xb8cBf1CC110c42C15CEf3CA0982b812a82d99613#code
TokenVesting: https://kovan.etherscan.io/address/0x915BBFBbA9C7090cd9622dE0157aE58EC4E3E802#code
PaymentSplitter: https://kovan.etherscan.io/address/0xfa6124374dc57302252ad8a6cd3d7879e0b4fcfa#code

**Comment by frangio** [comment]
We no longer publish predeployed contracts.
