### ISSUE TITLE
Unused function parameters in unchained initializers

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts-upgradeable#89]
There are unused function parameters in the unchained initializers in the Preset contracts

**💻 Environment**
OpenZeppelin Contracts Ethereum Package v3.0.0

**📝 Details**

Reported on Telegram (see forum post: https://forum.openzeppelin.com/t/unused-function-parameters-in-preset-contracts-in-openzeppelin-contracts-ethereum-package/2906)

The preset contracts have unused function parameters (`name` and `symbol`) in the unchained initializers.

https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/blob/v3.0.0/contracts/presets/ERC20PresetMinterPauser.sol#L49

https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/blob/v3.0.0/contracts/presets/ERC721PresetMinterPauserAutoId.sol#L57

**🔢 Code to reproduce bug**

## MyNFT.sol
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.2;

import "@openzeppelin/contracts-ethereum-package/contracts/Initializable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/presets/ERC721PresetMinterPauserAutoId.sol";


contract MyNFT is Initializable, ERC721PresetMinterPauserAutoIdUpgradeSafe {
    function initialize() public initializer {
        ERC721PresetMinterPauserAutoIdUpgradeSafe.initialize(
            "MyNFT",
            "MYN",
            "https://example.com/token/"
        );
    }
}
```

## Compiler warnings
```
$ npx oz compile
✓ Compiled contracts with solc 0.6.7 (commit.b8d736ae)
Compilation warnings:
@openzeppelin/contracts-ethereum-package/contracts/presets/ERC721PresetMinterPauserAutoId.sol:57:62: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function __ERC721PresetMinterPauserAutoId_init_unchained(string memory name, string memory symbol, string memory baseURI) internal initializer {
                                                             ^----------------^

@openzeppelin/contracts-ethereum-package/contracts/presets/ERC721PresetMinterPauserAutoId.sol:57:82: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function __ERC721PresetMinterPauserAutoId_init_unchained(string memory name, string memory symbol, string memory baseURI) internal initializer {
                                                                                 ^------------------^
```

**Comment by frangio** [comment]
For anyone seeing this, we know that this is an issue but the code in this repo is generated using an automated tool that I hope we can make public as soon as possible. But this means that any unused function parameters or style issues are due to the tool, and should be fixed there, rather than in the code in the repo.

We don't have a timeline for this yet.

**Comment by frangio** [comment]
For anyone seeing this, we know that these warnings are annoying, and the reason we are not fixing it is that the code in this repo is generated based on [OpenZeppelin Contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) using a tool. This means that unused function parameters should be removed by the tool and not manually. It's a feature that we have yet to build. I can't promise a timeline but we're working on this and hopefully we can make the tool public and remove these warnings soon.

**Comment by frangio** [comment]
The transpiler we use to generate this code is now open source and can be found in [OpenZeppelin/openzeppelin-transpiler](https://github.com/OpenZeppelin/openzeppelin-transpiler).

Unused function arguments are still not removed, but I plan to do this relatively soon.

**Comment by frangio** [comment]
This is fixed now and will be included in the next release.
