### ISSUE TITLE
Lint errors on master branch

### ISSUE THREAD

**Issue by julianmrodri** [OpenZeppelin/openzeppelin-contracts-upgradeable#96]
When running `npm run lint` you get several warnings and 9 errors (see screenshot below)

![image](https://user-images.githubusercontent.com/56316686/90212903-daab1980-ddca-11ea-9d64-c7125eb50e51.png)

This PR is intended to fix only the `errors`, as I understand the warnings are related to well known naming conventions defined by the OZ team (mainly `camelCase` naming requirement).

**IMPORTANT NOTE**: One of the errors was related to naming of `private` variables in the `Initialize.sol` contract which is extremely crucial. Even though they do not represent API or breaking changes should be double-checked if this contract wants to be modified.

**💻 Environment**

Repo: `@openzeppelin/open-zeppelin-contracts-ethereum-package`
Version: 3.0.0`
Branch: `master`

**📝 Details**

**🔢 Code to reproduce bug**
1 - Clone repo - `master` branch
2 - `npm install`
3- `npm run lint`

**Comment by frangio** [comment]
I've disabled lint checks on this repo since the code is generated automatically.
