### ISSUE TITLE
Add documentation on how to use

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts-upgradeable#99]
**🧐 Motivation**
Feedback in the Community Forum: https://forum.openzeppelin.com/t/how-to-use-ownable-with-upgradeable-contract/3336/8

**📝 Details**
1. Add documention on the docsite on how to use:
2. What to import
3. What to extend (UpgradeSafe version) and `Initializable` (and in what order)
4. What Initializers to call from dependencies

**Comment by frangio** [comment]
Published at https://docs.openzeppelin.com/contracts/upgradeable.
